### ISSUE TITLE
Faire tester le code par Symfony Insight

### ISSUE THREAD

**Issue by dgueudre** [Naime-m/P5_blog_php#16]
https://insight.symfony.com/

**Comment by dgueudre** [comment]
Test effectué
Maintenant, il faut corriger les erreurs

**Comment by Naime-m** [comment]
Plus d'erreurs majeurs

**Comment by Naime-m** [comment]
Silver Medal: SymfonyInsight found minor suggestions on this project. Fix them to get the Gold medal.24/100

Analyzed 7 minutes ago by medjeknaime, duration: a minute
P5_blog_php #32 develop
12 Minor 14 Info
10 Reliability 15 Productivity 1 Reputation

2.2 weeks to get the Platinum Medal

work for 2 weeks to get the Gold Medal

**Comment by Naime-m** [comment]
Votre projet devra être suivi via SymfonyInsight, ou Codacy pour la qualité du code. Vous veillerez à obtenir une médaille d'argent au minimum (pour SymfonyInsight)
Objectif atteint
