### ISSUE TITLE
Système de validation des commentaires

### ISSUE THREAD

**Issue by Naime-m** [Naime-m/P5_blog_php#23]
ajouter dans le menu pour les admin le lien "commentaires à valider"
route + ..... pour afficher la liste des commentaires à valider CommentRepository::getAllByStatus($status)

dans la vue, pour chaque ligne, il faut un bouton valider qui renvoi vers la route ?action=comment.valid&id=toto

gerer la route valider qui va appeler une fonction CommentRepository::updateStatus($status) +redirection vers la liste des commentaires à valider

---- dans le post.show il faudra utiliser la fonction CommentRepository::getAllByStatus($status)

**Comment by Naime-m** [comment]
2 x 6h

**Comment by Naime-m** [comment]
Problème dans la route 
Function getCommentStatus() -> récupération du statut du commentaire

**Comment by dgueudre** [comment]
N'oublie pas de push ton code si tu veux de l'aide :)

**Comment by Naime-m** [comment]
C'est fait ! :)

**Comment by Naime-m** [comment]
Fatal error: Uncaught Exception: Aucun statut de commentaire envoyé in C:\wamp64\www\P5_blog_php\src\app.php on line 57

**Comment by dgueudre** [comment]
si tu ne sais pas quoi mettre dans les paramètres que tu envoies à une fonction, mets une valeur fixe pour commencer
tu peux mettre 'toto' ou 1 par exemple

Si tu ne sais pas quoi mettre dans une fonction, c'est peut être qu'elle ne sert à rien

Pour que je comprenne bien ce que tu veux faire, explique moi exactement ce que tu veux faire
A quoi sert la fonction ? a quoi sert le paramètre ?

**Comment by Naime-m** [comment]
Comme je renvoie $status dans le Controller, actionShow  dans le router
demande une valeur, c'est pour ça que j'ai créé une fonction afin qu'elle
me renvoie l'id de statut d'un commentaire
Mais je ne sais pas si elle sert vraiment à quelque chose

**Comment by dgueudre** [comment]
dans ton dernier commit, tu as mis $_GET['comment_status_id'] pourquoi comment_status_id ?
A quoi ça sert $_GET ?

**Comment by Naime-m** [comment]
$_GET sert à récupérer un paramètre dans l'url. J'ai mis comment_status_id car c'était le seul paramètre qui me paraissait "correct" mais j'ai du me tromper

**Comment by dgueudre** [comment]
Comment tu fais pour vérifier qu'un paramètre existe dans l'URL ?

**Comment by Naime-m** [comment]
J'ai essayé quelques modifications mais je n'arrive pas à trouver là où ça
bloque je continuerais demain

**Comment by dgueudre** [comment]
C'est plus fiable de regarder l'URL

**Comment by Naime-m** [comment]
Je n'arrive pas à voir comment on peut vérifier directement dans l'URL

**Comment by Naime-m** [comment]
Sauf peut-être dans l'action

**Comment by Naime-m** [comment]
Je bloque au niveau du $status, je n'arrive pas à voir ce qu'il doit contenir

**Comment by dgueudre** [comment]
> Je n'arrive pas à voir comment on peut vérifier directement dans l'URL

Pour voir l'url, il faut que tu regarde dans la barre d'adresse de ton navigateur au moment ou il t'affiche l'erreur

**Comment by dgueudre** [comment]
> Je bloque au niveau du $status, je n'arrive pas à voir ce qu'il doit contenir

si tu ne sais pas ce que doit contenir $status, ne l'utilise pas... au pire, tu mets une valeur en dur

**Comment by Naime-m** [comment]
Je l'ai supprimé merci. Je vais y arriver !

**Comment by dgueudre** [comment]
ok, top,

sinon, si tu veux savoir ce qu'il y a dans $_GET, tu peux aussi faire var_dump($_GET) et pareil avec $_POST et $_SESSION si besoin
