### ISSUE TITLE
Sécuriser les mots de passe dans la base de données

### ISSUE THREAD

**Issue by dgueudre** [Naime-m/P5_blog_php#24]

**Comment by Naime-m** [comment]
Mot de passe crypté mais ne se connecte qu'avec celui-ci

**Comment by Naime-m** [comment]
Problème de mot de passe : 
Pour l'inscription le mot de passe s'affiche bien en crypté 
Pour la connexion, on ne peut se connecter qu'avec celui-ci et non le mot de passe en clair

**Comment by Naime-m** [comment]
Je ne sais pas si le souci vient de ma requête sql insert ou bien de celle getOnebyEmailandPassword: la requete insert insère bien un mot de passe crypté dans la bdd mais j'ai l'impression qu'elle l'insère en dur

**Comment by dgueudre** [comment]
Normalement, quand le user se connecte, au moment où tu test le mot de
passe, il faut que tu prenne le mot de passe non encrypté du POST et que tu
l'encrypte de la même façon que l'encryption de la bdd puis dans la
requête, tu compares le password encrypté qui vient du POST avec le
password encrypté qui est dans la base de données

**Comment by dgueudre** [comment]
Oui le mot de passe dans la base de données doit être stocké encrypté, donc
je pense que l'insert est bon

**Comment by Naime-m** [comment]
Très bien merci beaucoup je vais revoir ce que vous m'avez dit

**Comment by Naime-m** [comment]
public function getOneByEmailandPassword($email, $password)
    {
        $db = $this->dbConnect();
        $query = $db->prepare('SELECT id, email, password, lastname, firstname, userType_id
        FROM users WHERE email =  ?  AND password =  ?');
        $hashpass = password_hash($password, PASSWORD_DEFAULT);
        if (password_verify($password, $hashpass)) {
            $query->execute([$email, $password]);
            $users = $query->fetchAll(\PDO::FETCH_CLASS, User::class);

            return $users[0] ?? false;
        }
 
Je pense que ça correspond à ce que vous m'avez dit mais je n'arrive pas à trouver d'où vient le problème

**Comment by Naime-m** [comment]
je vais regarder du côté du controller je pense que ce doit être là bas que quelque chose cloche

**Comment by Naime-m** [comment]
Je ne comprends pas : malgré les conditions pour se connecter ça fonctionne même avec un $user false

**Comment by dgueudre** [comment]
tu peux me mettre le lien du cours que tu as suivi pour que je compare avec ce que tu as fait ?

**Comment by Naime-m** [comment]
Oui, bien sûr : 
https://stackoverflow.com/questions/30279321/how-to-use-phps-password-hash-to-hash-and-verify-passwords

**Comment by Naime-m** [comment]
J'ai aussi regardé ici :  https://www.php.net/manual/fr/function.password-hash

**Comment by dgueudre** [comment]
Alors, le problème dans ton code, c'est : 
* tu ne dois pas spécifier le password dans la requête et récuperer tous les user avec la bonne email (normalement 1 seul)
* ensuite, tu dois comparer avec *password_verify* le password non haché (qui vient de POST) avec le password haché (qui vient de la base de données)

**Comment by Naime-m** [comment]
public function getOneByEmailandPassword($email, $password)
    {
        $db = $this->dbConnect();
        $query = $db->prepare('SELECT id, email, password, lastname, firstname, userType_id
        FROM users WHERE email =  ?');
        $password = $_POST['password'];
        $hashpass = password_verify($password, PASSWORD_DEFAULT);
        if (password_verify($password, $hashpass)) {
            $query->execute([$email, $password]);
            $users = $query->fetchAll(\PDO::FETCH_CLASS, User::class);

            return $users[0] ?? false;
        } else {
            echo 'Mot de passe erroné';
        }
    }
J'ai quelque chose comme ça

**Comment by dgueudre** [comment]
Oui, relis bien ce que j'ai mis, ce que tu as fait ne correspond pas.
Tes erreurs:
* tu ne fais pas les choses dans l'ordre que j'ai écrit
* tu ne compares pas les bonnes données avec la fonction *password_verify*
Comme ça peut prêter à confusion, je réécris mon message en plus clair : 
1. récuperer tous les users avec la bonne email (normalement 1 seul)
2. ensuite, tu dois comparer avec password_verify le password non haché (qui vient de POST) avec le password haché (qui vient de la base de données)

**Comment by Naime-m** [comment]
Merci beaucoup, j'ai corrigé, ça donne ça :

public function getOneByEmailandPassword($email)
    {
        $db = $this->dbConnect();
        $query = $db->prepare('SELECT id, email, password, lastname, firstname, userType_id
        FROM users WHERE email =  ?');
        $query->execute([$email]);
        $users = $query->fetchAll(\PDO::FETCH_CLASS, User::class);
        $hashpass = password_verify($_POST['password'], PASSWORD_DEFAULT);
        if (password_verify($_POST['password'], $hashpass)) {
            return $users[0] ?? false;
        } else {
            echo 'Mot de passe erroné';
        }

**Comment by Naime-m** [comment]
Ah non mince, le mot de passe dans $hashpass ne vient pas de la base de données !

**Comment by Naime-m** [comment]
public function getOneByEmailandPassword($email)
    {
        $db = $this->dbConnect();
        $query = $db->prepare('SELECT id, email, password, lastname, firstname, userType_id
        FROM users WHERE email =  ?');
        $query->execute([$email]);
        $users = $query->fetchAll(\PDO::FETCH_CLASS, User::class);
        $hashpass = password_verify($users[0]->password, PASSWORD_DEFAULT);
        if (password_verify($_POST['password'], $hashpass)) {
            return $users[0] ?? false;
        } else {
            echo 'Mot de passe erroné';
        }

**Comment by Naime-m** [comment]
Je ne vois pas autrement..

**Comment by Naime-m** [comment]
PS : Ce morceau de code ne marche pas

**Comment by dgueudre** [comment]
je te laisse chercher jusqu'a demain, normalement, tu as toute les infos, simplifie les choses pour que ça corresponde bien a ce que j'ai écrit

**Comment by Naime-m** [comment]
Pas de soucis, merci encore ! :)
