### ISSUE TITLE
Tester le formulaire de contact

### ISSUE THREAD

**Issue by Naime-m** [Naime-m/P5_blog_php#26]

**Comment by Naime-m** [comment]
Ne fonctionne ni en local ni en ligne

**Comment by dgueudre** [comment]
je t'invite à tester avec l'exemple le plus simple possible que tu trouves sur la page de documentation php de la fonction mail

**Comment by Naime-m** [comment]
Très bien je vais essayer merci beaucoup !

**Comment by Naime-m** [comment]
Warning: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\wamp64\www\P5_blog_php\src\View\contact.submit.php on line 11

**Comment by dgueudre** [comment]
et en ligne ?

**Comment by Naime-m** [comment]
aucune erreur pour le mail(), mais je ne reçois rien. J'ai du mal
transférer les fichiers car j'ai plein d'erreur HTTP 500 dans le site
